<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product; // Your Product model

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        Product::truncate(); // Optional: Deletes all existing products first

        $products = [
            [
                "sku" => "SAP-LWN-001",
                "title" => "Embroidered Lawn Kurti",
                "description" => "A beautifully embroidered lawn kurti, perfect for casual summer outings. Features intricate thread work on the neckline and sleeves.",
                "brand" => "Sapphire",
                "price" => 3490.00,
                "type" => "Women",
                "categories" => ["Pret", "Kurtis", "Summer Collection"],
                "image" => "/images/products/sapphire-kurti-01.jpg",
                "sizes" => ["XS", "S", "M", "L"],
                "stock" => 120,
                "ratings" => 4.8,
                "discount" => 10,
                "is_featured" => true,
                "status" => "active",
                "views" => 0
            ],
            [
                "sku" => "KHA-CTN-002",
                "title" => "Classic Fit Cotton Kurta",
                "description" => "A classic men's kurta made from premium quality cotton. Simple, elegant, and comfortable for daily wear.",
                "brand" => "Khaadi",
                "price" => 2990.00,
                "type" => "Men",
                "categories" => ["Men's Fashion", "Kurtas", "Traditional"],
                "image" => "/images/products/khaadi-kurta-men-01.jpg",
                "sizes" => ["S", "M", "L", "XL"],
                "stock" => 150,
                "ratings" => 4.7,
                "discount" => 0,
                "is_featured" => true,
                "status" => "active",
                "views" => 0
            ],
            [
                "sku" => "GUL-SLK-003",
                "title" => "Printed Silk Tunic",
                "description" => "An elegant printed silk tunic with a modern silhouette. Perfect for evening wear and formal gatherings.",
                "brand" => "Gul Ahmed",
                "price" => 5990.00,
                "type" => "Women",
                "categories" => ["Pret", "Tops", "Formal Wear"],
                "image" => "/images/products/gul-ahmed-tunic-01.jpg",
                "sizes" => ["S", "M", "L"],
                "stock" => 75,
                "ratings" => 4.9,
                "discount" => 15,
                "is_featured" => true,
                "status" => "active",
                "views" => 0
            ],
            [
                "sku" => "ETH-CHN-004",
                "title" => "Men's Casual Chinos",
                "description" => "Comfortable and stylish slim-fit chinos for men. Made with a slight stretch for all-day comfort.",
                "brand" => "Ethnic",
                "price" => 3200.00,
                "type" => "Men",
                "categories" => ["Men's Fashion", "Bottoms", "Western"],
                "image" => "/images/products/ethnic-chinos-01.jpg",
                "sizes" => ["30", "32", "34", "36"],
                "stock" => 200,
                "ratings" => 4.5,
                "discount" => 0,
                "is_featured" => false,
                "status" => "active",
                "views" => 0
            ],
            [
                "sku" => "ALK-VSC-005",
                "title" => "Digital Printed Viscose Shirt",
                "description" => "A vibrant digitally printed viscose shirt for women, featuring a contemporary design and a relaxed fit.",
                "brand" => "Alkaram Studio",
                "price" => 2750.00,
                "type" => "Women",
                "categories" => ["Pret", "Tops"],
                "image" => "/images/products/alkaram-shirt-01.jpg",
                "sizes" => ["S", "M", "L", "XL"],
                "stock" => 180,
                "ratings" => 4.6,
                "discount" => 0,
                "is_featured" => false,
                "status" => "active",
                "views" => 0
            ],
            [
                "sku" => "J-WST-006",
                "title" => "Men's Embroidered Waistcoat",
                "description" => "A formal embroidered waistcoat for men, crafted from jamawar fabric. Ideal for weddings and festive occasions.",
                "brand" => "J.",
                "price" => 7500.00,
                "type" => "Men",
                "categories" => ["Men's Fashion", "Formal Wear", "Waistcoats"],
                "image" => "/images/products/j-waistcoat-01.jpg",
                "sizes" => ["S", "M", "L"],
                "stock" => 60,
                "ratings" => 4.9,
                "discount" => 0,
                "is_featured" => true,
                "status" => "active",
                "views" => 0
            ],
            [
                "sku" => "SAP-CMB-007",
                "title" => "Solid Color Cambric Trousers",
                "description" => "Versatile solid color cambric trousers for women. A wardrobe staple that pairs well with any kurti or tunic.",
                "brand" => "Sapphire",
                "price" => 1490.00,
                "type" => "Women",
                "categories" => ["Bottoms", "Trousers"],
                "image" => "/images/products/sapphire-trousers-01.jpg",
                "sizes" => ["XS", "S", "M", "L", "XL"],
                "stock" => 300,
                "ratings" => 4.4,
                "discount" => 0,
                "is_featured" => false,
                "status" => "active",
                "views" => 0
            ],
            [
                "sku" => "OUTF-POL-008",
                "title" => "Men's Basic Polo Shirt",
                "description" => "A classic polo shirt in pique cotton. Available in multiple colors for a smart-casual look.",
                "brand" => "Outfitters",
                "price" => 1990.00,
                "type" => "Men",
                "categories" => ["Men's Fashion", "T-Shirts", "Western"],
                "image" => "/images/products/outfitters-polo-01.jpg",
                "sizes" => ["S", "M", "L", "XL"],
                "stock" => 250,
                "ratings" => 4.6,
                "discount" => 5,
                "is_featured" => false,
                "status" => "active",
                "views" => 0
            ],
            [
                "sku" => "NSH-UNS-009",
                "title" => "Unstitched 3-Piece Lawn Suit",
                "description" => "An elegant 3-piece unstitched lawn suit with a chiffon dupatta. Perfect for creating a custom outfit.",
                "brand" => "Nishat Linen",
                "price" => 4200.00,
                "type" => "Women",
                "categories" => ["Unstitched", "Lawn", "3-Piece Suit"],
                "image" => "/images/products/nishat-unstitched-01.jpg",
                "sizes" => ["One Size"],
                "stock" => 100,
                "ratings" => 4.8,
                "discount" => 20,
                "is_featured" => false,
                "status" => "active",
                "views" => 0
            ],
            [
                "sku" => "LVS-JNS-010",
                "title" => "Straight Cut Denim Jeans",
                "description" => "Classic straight cut denim jeans for men with a vintage wash. Durable and stylish for everyday use.",
                "brand" => "Levi's",
                "price" => 6500.00,
                "type" => "Men",
                "categories" => ["Men's Fashion", "Bottoms", "Jeans"],
                "image" => "/images/products/levis-jeans-01.jpg",
                "sizes" => ["30", "32", "34", "36", "38"],
                "stock" => 90,
                "ratings" => 4.7,
                "discount" => 0,
                "is_featured" => false,
                "status" => "active",
                "views" => 0
            ],
            [
                "sku" => "ETH-CHK-011",
                "title" => "Chikankari Kurti",
                "description" => "Hand-embroidered Chikankari kurti on soft georgette fabric. A timeless piece of traditional craftsmanship.",
                "brand" => "Ethnic",
                "price" => 8990.00,
                "type" => "Women",
                "categories" => ["Pret", "Kurtis", "Formal Wear", "Handcrafted"],
                "image" => "/images/products/ethnic-chikankari-01.jpg",
                "sizes" => ["S", "M", "L"],
                "stock" => 40,
                "ratings" => 5.0,
                "discount" => 0,
                "is_featured" => true,
                "status" => "active",
                "views" => 0
            ],
            [
                "sku" => "KHA-SCRF-012",
                "title" => "Printed Linen Scarf",
                "description" => "A soft and lightweight printed linen scarf. The perfect accessory to complete your look.",
                "brand" => "Khaadi",
                "price" => 1290.00,
                "type" => "Women",
                "categories" => ["Accessories", "Scarves"],
                "image" => "/images/products/khaadi-scarf-01.jpg",
                "sizes" => ["One Size"],
                "stock" => 150,
                "ratings" => 4.5,
                "discount" => 0,
                "is_featured" => false,
                "status" => "active",
                "views" => 0
            ],
            [
                "sku" => "STY-SNDL-013",
                "title" => "Men's Leather Sandals",
                "description" => "Handcrafted leather sandals for men, combining traditional design with modern comfort.",
                "brand" => "Stylo",
                "price" => 2490.00,
                "type" => "Men",
                "categories" => ["Men's Fashion", "Footwear", "Sandals"],
                "image" => "/images/products/stylo-sandals-01.jpg",
                "sizes" => ["8", "9", "10", "11"],
                "stock" => 110,
                "ratings" => 4.3,
                "discount" => 0,
                "is_featured" => false,
                "status" => "active",
                "views" => 0
            ],
            [
                "sku" => "GUL-JCQ-014",
                "title" => "Jacquard 2-Piece Suit",
                "description" => "A sophisticated 2-piece jacquard suit for women, featuring rich texture and a tailored fit.",
                "brand" => "Gul Ahmed",
                "price" => 6250.00,
                "type" => "Women",
                "categories" => ["Pret", "2-Piece Suit", "Winter Collection"],
                "image" => "/images/products/gul-ahmed-jacquard-01.jpg",
                "sizes" => ["XS", "S", "M"],
                "stock" => 85,
                "ratings" => 4.8,
                "discount" => 10,
                "is_featured" => false,
                "status" => "active",
                "views" => 0
            ],
            [
                "sku" => "CGR-TEE-015",
                "title" => "Men's Graphic Tee",
                "description" => "A comfortable cotton graphic t-shirt with a unique print. Perfect for a casual, laid-back style.",
                "brand" => "Cougar",
                "price" => 1790.00,
                "type" => "Men",
                "categories" => ["Men's Fashion", "T-Shirts", "Western"],
                "image" => "/images/products/cougar-tee-01.jpg",
                "sizes" => ["S", "M", "L", "XL"],
                "stock" => 220,
                "ratings" => 4.5,
                "discount" => 0,
                "is_featured" => false,
                "status" => "active",
                "views" => 0
            ]
        ];

        foreach ($products as $productData) {
            Product::create($productData);
        }
    }
}